# Markdown Linting Configuration
# Désactive les règles cosmétiques pour ThreadX

# Headings
MD022: false # Headings should be surrounded by blank lines
MD026: false # Trailing punctuation in heading

# Lists
MD032: false # Lists should be surrounded by blank lines

# Code blocks
MD031: false # Fenced code blocks should be surrounded by blank lines
MD040: false # Fenced code blocks should have a language specified

# Line length (adapté au contenu technique)
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Autres règles permissives
MD024: false # Multiple headings with the same content
MD033: false # Inline HTML
MD041: false # First line in file should be a top level heading
