# ThreadX - Configuration par défaut
[paths]
data = "data"
cache = "data/cache"
logs = "logs"

[performance]
workers = 4
gpu = false

[data]
source = "stub"

[udi]
json_root = 'D:\\ThreadX_big\\src\\threadx\\data\\crypto_data_json'
parquet_root = 'D:\\ThreadX_big\\src\\threadx\\data\\crypto_data_parquet'
indicators_db_root = 'D:\\ThreadX_big\\src\\threadx\\data\\indicateurs_data_parquet'
output_dir = 'D:\\ThreadX_big\\src\\threadx\\data'
rate_limit_per_sec = 10
request_timeout_sec = 30
