# ThreadX Configuration File
# Phase 1: Configuration and Paths
# Version: 1.0
# Date: 2025-09-30

[paths]
# Chemins relatifs uniquement - pas de chemins absolus
data_root = "./data"
raw_json = "{data_root}/raw/json"
processed = "{data_root}/processed"
indicators = "{data_root}/indicators"
runs = "{data_root}/runs"
logs = "./logs"
cache = "./cache"
config = "./config"

[gpu] 
# Configuration GPU multi-cartes
devices = ["5090", "2060"]
load_balance = {"5090" = 0.75, "2060" = 0.25}
memory_threshold = 0.8
auto_fallback = true
enable_gpu = true

[performance]
# Paramètres de performance
target_tasks_per_min = 2500
vectorization_batch_size = 10000
cache_ttl_sec = 3600
max_workers = 4
memory_limit_mb = 8192

[trading]
# Configuration trading
supported_timeframes = ["1m", "3m", "5m", "15m", "30m", "1h", "2h", "4h", "6h", "8h", "12h", "1d"]
default_timeframe = "1h"
base_currency = "USDT"
fee_rate = 0.001
slippage_rate = 0.0005

[backtesting]
# Paramètres de backtesting
initial_capital = 10000.0
max_positions = 10
position_size = 0.1
stop_loss = 0.02
take_profit = 0.04

[logging]
# Configuration des logs
level = "INFO"
max_file_size_mb = 100
max_files = 10
rotate = true
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

[security]
# Règles de sécurité
read_only_data = true
validate_paths = true
allow_absolute_paths = false
max_file_size_mb = 1000

[monte_carlo]
# Configuration Monte Carlo
default_simulations = 10000
max_simulations = 1000000
default_steps = 252
seed = 42
confidence_levels = [0.95, 0.99]

[cache]
# Configuration cache
enable = true
max_size_mb = 2048
ttl_seconds = 3600
compression = true
strategy = "LRU"